name: 自定义编译 RustDesk (可选择平台)
on:
  workflow_dispatch:
    inputs:
      build_windows:
        description: 编译 Windows (x64) Flutter新版
        required: true
        default: true
        type: boolean
      build_windows_sciter:
        description: 编译 Windows (x86) Sciter旧版
        required: true
        default: true
        type: boolean
      build_macos:
        description: 编译 macOS (x64 + arm64)
        required: true
        default: true
        type: boolean
      build_android:
        description: 编译 Android
        required: true
        default: true
        type: boolean
      build_linux:
        description: 编译 Linux (x64 + arm64)
        required: true
        default: true
        type: boolean
      upload-artifact:
        type: boolean
        default: true
      upload-tag:
        type: string
        default: "custom-build"

env:
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  MAC_RUST_VERSION: "1.81"
  CARGO_NDK_VERSION: "3.1.2"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  ANDROID_FLUTTER_VERSION: "3.24.5"
  FLUTTER_ELINUX_VERSION: "3.16.9"
  TAG_NAME: "${{ inputs.upload-tag }}"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4850575a33844ba10b"
  ARMV7_VCPKG_COMMIT_ID: "6f29f12e82a8293156836ad81cc9bf5af41fe836"
  VERSION: "1.4.6"
  NDK_VERSION: "r28c"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

# ========================= Windows Flutter 新版 =========================
  build-for-windows-flutter:
    if: ${{ inputs.build_windows }}
    name: Windows x64 Flutter
    needs: [generate-bridge]
    runs-on: windows-2022
    steps:
      - uses: actions/github-script@v6
        with: 
          script: "core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || ''); core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');"
      
      - name: Configure Git mirror
        run: |
          git config --global url."https://github.com/jbeich/aom.git".insteadOf https://aomedia.googlesource.com/aom
      
      - uses: actions/checkout@v4
        with: 
          submodules: recursive

      - uses: actions/download-artifact@master
        with: 
          name: bridge-artifact
          path: ./
          
      - uses: KyleMayes/install-llvm-action@v1
        with: 
          version: "${{ env.LLVM_VERSION }}"
          
      - uses: subosito/flutter-action@v2
        with: 
          channel: "stable"
          flutter-version: "${{ env.FLUTTER_VERSION }}"

      - name: Build Flutter
        run: |
          flutter doctor -v
          flutter precache --windows
          
      - uses: dtolnay/rust-toolchain@v1
        with: 
          toolchain: "${{ env.SCITER_RUST_VERSION }}"
          targets: "x86_64-pc-windows-msvc"
          
      - uses: Swatinem/rust-cache@v2
      
      - uses: lukka/run-vcpkg@v11
        with: 
          vcpkgDirectory: "C:\\vcpkg"
          vcpkgGitCommitId: "${{ env.VCPKG_COMMIT_ID }}"

      - name: Install dependencies
        shell: bash
        run: $VCPKG_ROOT/vcpkg install libvpx libyuv opus aom --triplet x64-windows-static

      - name: Compile
        run: python3 .\build.py --portable --hwcodec --flutter --vram --skip-portable-pack

      - uses: microsoft/setup-msbuild@v2
      
      - name: Build MSI
        run: |
          cd res/msi
          nuget restore msi.sln
          msbuild msi.sln -p:Configuration=Release -p:Platform=x64 -p:TargetVersion=Windows10

      - uses: ncipollo/release-action@v1
        with:
          prerelease: true
          tag: "${{ env.TAG_NAME }}"
          artifacts: "flutter/build/windows/x64/runner/Release/*.exe,res/msi/bin/x64/Release/*.msi"
          token: ${{ secrets.GITHUB_TOKEN }}

# ========================= Windows Sciter 32位 =========================
  build-for-windows-sciter:
    if: ${{ inputs.build_windows_sciter }}
    name: Windows x86 Sciter
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: recursive
          
      - name: Configure Git mirror
        run: |
          git config --global url."https://github.com/jbeich/aom.git".insteadOf https://aomedia.googlesource.com/aom
      
      - uses: dtolnay/rust-toolchain@v1
        with: 
          toolchain: nightly-2023-10-13-i686-pc-windows-msvc
          targets: "i686-pc-windows-msvc"
          
      - uses: lukka/run-vcpkg@v11
        with: 
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: "${{ env.VCPKG_COMMIT_ID }}"

      - name: Install deps
        shell: bash
        run: $VCPKG_ROOT/vcpkg install libvpx libyuv opus aom --triplet x86-windows-static

      - name: Build
        run: |
          python res/inline-sciter.py
          cargo build --features inline,vram,hwcodec --release --target i686-pc-windows-msvc

      - uses: ncipollo/release-action@v1
        with:
          prerelease: true
          tag: "${{ env.TAG_NAME }}"
          artifacts: "target/i686-pc-windows-msvc/release/rustdesk.exe"
          token: ${{ secrets.GITHUB_TOKEN }}

# ========================= macOS =========================
  build-for-macOS:
    if: ${{ inputs.build_macos }}
    name: macOS
    needs: [generate-bridge]
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: recursive
      
      - name: Configure Git mirror
        run: git config --global url."https://github.com/jbeich/aom.git".insteadOf https://aomedia.googlesource.com/aom
        
      - run: brew install llvm create-dmg nasm
      - uses: dtolnay/rust-toolchain@v1
        with: 
          toolchain: "${{ env.MAC_RUST_VERSION }}"
          
      - uses: lukka/run-vcpkg@v11
        with: 
          vcpkgGitCommitId: "${{ env.VCPKG_COMMIT_ID }}"
        
      - run: vcpkg install libvpx libyuv opus aom
      - run: ./build.py --flutter --hwcodec --unix-file-copy-paste
      - run: create-dmg rustdesk.dmg flutter/build/macos/Build/Products/Release/RustDesk.app
      
      - uses: ncipollo/release-action@v1
        with:
          prerelease: true
          tag: "${{ env.TAG_NAME }}"
          artifacts: "rustdesk.dmg"
          token: ${{ secrets.GITHUB_TOKEN }}

# ========================= Android =========================
  build-rustdesk-android:
    if: ${{ inputs.build_android }}
    needs: [generate-bridge]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: recursive
      
      - name: Configure Git mirror
        run: git config --global url."https://github.com/jbeich/aom.git".insteadOf https://aomedia.googlesource.com/aom
        
      - run: sudo apt install -y clang cmake ninja-build nasm openjdk-17-jdk-headless
      - uses: nttld/setup-ndk@v1
        with: 
          ndk-version: "${{ env.NDK_VERSION }}"
          
      - uses: dtolnay/rust-toolchain@v1
        with: 
          toolchain: "${{ env.RUST_VERSION }}"
          
      - run: |
          rustup target add aarch64-linux-android armv7-linux-androideabi x86_64-linux-android
          ./flutter/build_android.sh
      
      - uses: ncipollo/release-action@v1
        with:
          prerelease: true
          tag: "${{ env.TAG_NAME }}"
          artifacts: "flutter/build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}

# ========================= Linux =========================
  build-rustdesk-linux:
    if: ${{ inputs.build_linux }}
    needs: [generate-bridge]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: recursive
      
      - name: Configure Git mirror
        run: git config --global url."https://github.com/jbeich/aom.git".insteadOf https://aomedia.googlesource.com/aom
        
      - uses: dtolnay/rust-toolchain@v1
        with: 
          toolchain: "${{ env.RUST_VERSION }}"
          
      - uses: lukka/run-vcpkg@v11
        with: 
          vcpkgDirectory: "/opt/artifacts/vcpkg"
          vcpkgGitCommitId: "${{ env.VCPKG_COMMIT_ID }}"
      
      - run: |
          vcpkg install libvpx libyuv opus aom
          cargo build --lib --features hwcodec,flutter --release
          ./build.py --flutter --skip-cargo
      
      - uses: ncipollo/release-action@v1
        with:
          prerelease: true
          tag: "${{ env.TAG_NAME }}"
          artifacts: "rustdesk-*.deb"
          token: ${{ secrets.GITHUB_TOKEN }}
